image: "python:3.8"

stages:
  - publish

publish_package:
  stage: publish
  script:
    - pip install twine
    - rm -rf dist/
    - python setup.py bdist_wheel
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  tags:
    - docker
  only:
    - tags
